"use strict";

module.exports = {
    getCountryRegion : getCountryRegion
}

//--------------------------------------------------------------------------------------------------
//--------------------------------------------------------------------------------------------------
// Region Map

var regionMap = [
    { countrycode : 'dz', region : 'AF' },
    { countrycode : 'ao', region : 'AF' },
    { countrycode : 'bj', region : 'AF' },
    { countrycode : 'bw', region : 'AF' },
    { countrycode : 'bf', region : 'AF' },
    { countrycode : 'bi', region : 'AF' },
    { countrycode : 'cm', region : 'AF' },
    { countrycode : 'cv', region : 'AF' },
    { countrycode : 'cf', region : 'AF' },
    { countrycode : 'td', region : 'AF' },
    { countrycode : 'km', region : 'AF' },
    { countrycode : 'cg', region : 'AF' },
    { countrycode : 'cd', region : 'AF' },
    { countrycode : 'ci', region : 'AF' },
    { countrycode : 'dj', region : 'AF' },
    { countrycode : 'eg', region : 'AF' },
    { countrycode : 'gq', region : 'AF' },
    { countrycode : 'er', region : 'AF' },
    { countrycode : 'et', region : 'AF' },
    { countrycode : 'ga', region : 'AF' },
    { countrycode : 'gm', region : 'AF' },
    { countrycode : 'gh', region : 'AF' },
    { countrycode : 'gn', region : 'AF' },
    { countrycode : 'gw', region : 'AF' },
    { countrycode : 'ke', region : 'AF' },
    { countrycode : 'ls', region : 'AF' },
    { countrycode : 'lr', region : 'AF' },
    { countrycode : 'ly', region : 'AF' },
    { countrycode : 'mg', region : 'AF' },
    { countrycode : 'mw', region : 'AF' },
    { countrycode : 'ml', region : 'AF' },
    { countrycode : 'mr', region : 'AF' },
    { countrycode : 'mu', region : 'AF' },
    { countrycode : 'yt', region : 'AF' },
    { countrycode : 'ma', region : 'AF' },
    { countrycode : 'mz', region : 'AF' },
    { countrycode : 'na', region : 'AF' },
    { countrycode : 'ne', region : 'AF' },
    { countrycode : 'ng', region : 'AF' },
    { countrycode : 're', region : 'AF' },
    { countrycode : 'rw', region : 'AF' },
    { countrycode : 'sh', region : 'AF' },
    { countrycode : 'st', region : 'AF' },
    { countrycode : 'sn', region : 'AF' },
    { countrycode : 'sc', region : 'AF' },
    { countrycode : 'sl', region : 'AF' },
    { countrycode : 'so', region : 'AF' },
    { countrycode : 'za', region : 'AF' },
    { countrycode : 'ss', region : 'AF' },
    { countrycode : 'sd', region : 'AF' },
    { countrycode : 'sz', region : 'AF' },
    { countrycode : 'tz', region : 'AF' },
    { countrycode : 'tg', region : 'AF' },
    { countrycode : 'tn', region : 'AF' },
    { countrycode : 'ug', region : 'AF' },
    { countrycode : 'eh', region : 'AF' },
    { countrycode : 'zm', region : 'AF' },
    { countrycode : 'zw', region : 'AF' },
    { countrycode : 'aq', region : 'AN' },
    { countrycode : 'bv', region : 'AN' },
    { countrycode : 'tf', region : 'AN' },
    { countrycode : 'hm', region : 'AN' },
    { countrycode : 'gs', region : 'AN' },
    { countrycode : 'af', region : 'AS' },
    { countrycode : 'am', region : 'AS' },
    { countrycode : 'az', region : 'AS' },
    { countrycode : 'bh', region : 'AS' },
    { countrycode : 'bd', region : 'AS' },
    { countrycode : 'bt', region : 'AS' },
    { countrycode : 'io', region : 'AS' },
    { countrycode : 'bn', region : 'AS' },
    { countrycode : 'kh', region : 'AS' },
    { countrycode : 'cn', region : 'AS' },
    { countrycode : 'cx', region : 'AS' },
    { countrycode : 'cc', region : 'AS' },
    { countrycode : 'cy', region : 'AS' },
    { countrycode : 'ge', region : 'AS' },
    { countrycode : 'hk', region : 'AS' },
    { countrycode : 'in', region : 'AS' },
    { countrycode : 'id', region : 'AS' },
    { countrycode : 'ir', region : 'AS' },
    { countrycode : 'iq', region : 'AS' },
    { countrycode : 'il', region : 'AS' },
    { countrycode : 'jp', region : 'AS' },
    { countrycode : 'jo', region : 'AS' },
    { countrycode : 'kz', region : 'EU' },
    { countrycode : 'kp', region : 'AS' },
    { countrycode : 'kr', region : 'AS' },
    { countrycode : 'kw', region : 'AS' },
    { countrycode : 'kg', region : 'AS' },
    { countrycode : 'la', region : 'AS' },
    { countrycode : 'lb', region : 'AS' },
    { countrycode : 'mo', region : 'AS' },
    { countrycode : 'my', region : 'AS' },
    { countrycode : 'mv', region : 'AS' },
    { countrycode : 'mn', region : 'AS' },
    { countrycode : 'mm', region : 'AS' },
    { countrycode : 'np', region : 'AS' },
    { countrycode : 'om', region : 'AS' },
    { countrycode : 'pk', region : 'AS' },
    { countrycode : 'ps', region : 'AS' },
    { countrycode : 'ph', region : 'AS' },
    { countrycode : 'qa', region : 'AS' },
    { countrycode : 'sa', region : 'AS' },
    { countrycode : 'sg', region : 'AS' },
    { countrycode : 'lk', region : 'AS' },
    { countrycode : 'sy', region : 'AS' },
    { countrycode : 'tw', region : 'AS' },
    { countrycode : 'tj', region : 'AS' },
    { countrycode : 'th', region : 'AS' },
    { countrycode : 'tl', region : 'AS' },
    { countrycode : 'tm', region : 'AS' },
    { countrycode : 'ae', region : 'AS' },
    { countrycode : 'uz', region : 'AS' },
    { countrycode : 'vn', region : 'AS' },
    { countrycode : 'ye', region : 'AS' },
    { countrycode : 'ax', region : 'EU' },
    { countrycode : 'al', region : 'EU' },
    { countrycode : 'ad', region : 'EU' },
    { countrycode : 'at', region : 'EU' },
    { countrycode : 'by', region : 'EU' },
    { countrycode : 'be', region : 'EU' },
    { countrycode : 'ba', region : 'EU' },
    { countrycode : 'bg', region : 'EU' },
    { countrycode : 'hr', region : 'EU' },
    { countrycode : 'cz', region : 'EU' },
    { countrycode : 'dk', region : 'EU' },
    { countrycode : 'ee', region : 'EU' },
    { countrycode : 'fo', region : 'EU' },
    { countrycode : 'fi', region : 'EU' },
    { countrycode : 'fr', region : 'EU' },
    { countrycode : 'de', region : 'EU' },
    { countrycode : 'gi', region : 'EU' },
    { countrycode : 'gr', region : 'EU' },
    { countrycode : 'gg', region : 'EU' },
    { countrycode : 'va', region : 'EU' },
    { countrycode : 'hu', region : 'EU' },
    { countrycode : 'is', region : 'EU' },
    { countrycode : 'ie', region : 'EU' },
    { countrycode : 'im', region : 'EU' },
    { countrycode : 'it', region : 'EU' },
    { countrycode : 'je', region : 'EU' },
    { countrycode : 'lv', region : 'EU' },
    { countrycode : 'li', region : 'EU' },
    { countrycode : 'lt', region : 'EU' },
    { countrycode : 'lu', region : 'EU' },
    { countrycode : 'mk', region : 'EU' },
    { countrycode : 'mt', region : 'EU' },
    { countrycode : 'md', region : 'EU' },
    { countrycode : 'mc', region : 'EU' },
    { countrycode : 'me', region : 'EU' },
    { countrycode : 'nl', region : 'EU' },
    { countrycode : 'no', region : 'EU' },
    { countrycode : 'pl', region : 'EU' },
    { countrycode : 'pt', region : 'EU' },
    { countrycode : 'ro', region : 'EU' },
    { countrycode : 'ru', region : 'EU' },
    { countrycode : 'sm', region : 'EU' },
    { countrycode : 'rs', region : 'EU' },
    { countrycode : 'sk', region : 'EU' },
    { countrycode : 'si', region : 'EU' },
    { countrycode : 'es', region : 'EU' },
    { countrycode : 'sj', region : 'EU' },
    { countrycode : 'se', region : 'EU' },
    { countrycode : 'ch', region : 'EU' },
    { countrycode : 'tr', region : 'EU' },
    { countrycode : 'ua', region : 'EU' },
    { countrycode : 'gb', region : 'EU' },
    { countrycode : 'xk', region : 'EU' },
    { countrycode : 'wls', region : 'EU' },
    { countrycode : 'ai', region : 'NA' },
    { countrycode : 'ag', region : 'NA' },
    { countrycode : 'aw', region : 'NA' },
    { countrycode : 'bs', region : 'NA' },
    { countrycode : 'bb', region : 'NA' },
    { countrycode : 'bz', region : 'NA' },
    { countrycode : 'bm', region : 'NA' },
    { countrycode : 'bq', region : 'NA' },
    { countrycode : 'ca', region : 'NA' },
    { countrycode : 'ky', region : 'NA' },
    { countrycode : 'cr', region : 'NA' },
    { countrycode : 'cu', region : 'NA' },
    { countrycode : 'cw', region : 'NA' },
    { countrycode : 'dm', region : 'NA' },
    { countrycode : 'do', region : 'NA' },
    { countrycode : 'sv', region : 'NA' },
    { countrycode : 'gl', region : 'NA' },
    { countrycode : 'gd', region : 'NA' },
    { countrycode : 'gp', region : 'NA' },
    { countrycode : 'gt', region : 'NA' },
    { countrycode : 'ht', region : 'NA' },
    { countrycode : 'hn', region : 'NA' },
    { countrycode : 'jm', region : 'NA' },
    { countrycode : 'mq', region : 'NA' },
    { countrycode : 'mx', region : 'NA' },
    { countrycode : 'ms', region : 'NA' },
    { countrycode : 'ni', region : 'NA' },
    { countrycode : 'pa', region : 'NA' },
    { countrycode : 'pr', region : 'NA' },
    { countrycode : 'bl', region : 'NA' },
    { countrycode : 'kn', region : 'NA' },
    { countrycode : 'lc', region : 'NA' },
    { countrycode : 'mf', region : 'NA' },
    { countrycode : 'pm', region : 'NA' },
    { countrycode : 'vc', region : 'NA' },
    { countrycode : 'sx', region : 'NA' },
    { countrycode : 'tt', region : 'NA' },
    { countrycode : 'tc', region : 'NA' },
    { countrycode : 'us', region : 'NA' },
    { countrycode : 'vg', region : 'NA' },
    { countrycode : 'vi', region : 'NA' },
    { countrycode : 'as', region : 'OC' },
    { countrycode : 'au', region : 'OC' },
    { countrycode : 'ck', region : 'OC' },
    { countrycode : 'fj', region : 'OC' },
    { countrycode : 'pf', region : 'OC' },
    { countrycode : 'gu', region : 'OC' },
    { countrycode : 'ki', region : 'OC' },
    { countrycode : 'mh', region : 'OC' },
    { countrycode : 'fm', region : 'OC' },
    { countrycode : 'nr', region : 'OC' },
    { countrycode : 'nc', region : 'OC' },
    { countrycode : 'nz', region : 'OC' },
    { countrycode : 'nu', region : 'OC' },
    { countrycode : 'nf', region : 'OC' },
    { countrycode : 'mp', region : 'OC' },
    { countrycode : 'pw', region : 'OC' },
    { countrycode : 'pg', region : 'OC' },
    { countrycode : 'pn', region : 'OC' },
    { countrycode : 'ws', region : 'OC' },
    { countrycode : 'sb', region : 'OC' },
    { countrycode : 'tk', region : 'OC' },
    { countrycode : 'to', region : 'OC' },
    { countrycode : 'tv', region : 'OC' },
    { countrycode : 'um', region : 'OC' },
    { countrycode : 'vu', region : 'OC' },
    { countrycode : 'wf', region : 'OC' },
    { countrycode : 'ar', region : 'SA' },
    { countrycode : 'bo', region : 'SA' },
    { countrycode : 'br', region : 'SA' },
    { countrycode : 'cl', region : 'SA' },
    { countrycode : 'co', region : 'SA' },
    { countrycode : 'ec', region : 'SA' },
    { countrycode : 'fk', region : 'SA' },
    { countrycode : 'gf', region : 'SA' },
    { countrycode : 'gy', region : 'SA' },
    { countrycode : 'py', region : 'SA' },
    { countrycode : 'pe', region : 'SA' },
    { countrycode : 'sr', region : 'SA' },
    { countrycode : 'uy', region : 'SA' },
    { countrycode : 've', region : 'SA' },    
];

function getCountryRegion( playerCountry ){
    let record = regionMap.find( el => el.countrycode.toLowerCase() === playerCountry.toLowerCase() );
    
    if (!record) {
        throw new Error( `Country region could not be found for ${playerCountry}` );
    }

    let region = record.region;

    if ( region === 'EU' ){
        return 0;
    }

    if ( region === 'NA' || region === 'SA' )
        return 1;

    return 2;
}